### ISSUE TITLE
INSERT_INTERVAL 没有用

### ISSUE THREAD

**Issue by lenovore** [long2ice/mysql2ch#1]
# how many num to submit
INSERT_NUMS=20000
# how many seconds to submit
INSERT_INTERVAL=60

即使过了60s，只要INSERT_NUMS没有达到设定的值，就不会提交！

**Comment by long2ice** [comment]
是不是最新的代码？

**Comment by lenovore** [comment]
好的，可能是因为容器时间的问题吧
这边正好遇到个问题，.env中PARTITIONS设置一个是没问题的（PARTITIONS=test.tb1=0;）
但是设置两个以后就报错（PARTITIONS=test.tb1=0;test.tb2=1;），麻烦看下是什么情况呢，我对kafka不太了解
![image](https://user-images.githubusercontent.com/29646774/79193260-dbec2a00-7e5c-11ea-9271-2b8fe4b99dcc.png)

**Comment by lenovore** [comment]
Traceback (most recent call last):
producer_1           |   File "manage.py", line 46, in <module>
producer_1           |     cli()
producer_1           |   File "manage.py", line 42, in cli
producer_1           |     parse_args.func(parse_args)
producer_1           |   File "/src/mysql2ch/producer.py", line 42, in produce
producer_1           |     key=key,
producer_1           |   File "/usr/local/site-packages/kafka/producer/kafka.py", line 576, in send
producer_1           |     key_bytes, value_bytes)
producer_1           |   File "/usr/local/site-packages/kafka/producer/kafka.py", line 715, in _partition
producer_1           |     available)
producer_1           |   File "/src/mysql2ch/__init__.py", line 22, in partitioner
producer_1           |     return all_partitions[partition]
producer_1           | IndexError: list index out of range

**Comment by lenovore** [comment]
解决了，没仔细看代码，以为.env中的分区增加脚本会自动修改kafka主体mysql2ch分区数量，原来还是得手动修改分区数量
