### ISSUE TITLE
删除过滤bug

### ISSUE THREAD

**Issue by lenovore** [long2ice/mysql2ch#2]
writer.py 第208->212行 应改为 
`if 'delete' not in skip_dmls_all and skip_dml_table_name not in skip_delete_tb_name:`

否则正常添加或更新可能会跟删除一起过滤掉

**Comment by long2ice** [comment]
![image](https://user-images.githubusercontent.com/13377178/79309301-a747a380-7f2c-11ea-88ff-093a01efeb0b.png)
这里吗？这里已经做好判断才执行的SQL

**Comment by lenovore** [comment]
应该用continue而不是return吧，不然整个循环都会退出

**Comment by lenovore** [comment]
当然出现问题的前提是配置中设置了 SKIP_DELETE_TB_NAME
一个批次有添加和删除，return后添加就无法执行了，如下图：
![image](https://user-images.githubusercontent.com/29646774/79312099-fb548700-7f30-11ea-9900-2b0d3bb8f17e.png)
正常的情况添加应该会有下面的提示
![image](https://user-images.githubusercontent.com/29646774/79312174-1626fb80-7f31-11ea-9a2b-1ac6e8df47a3.png)

**Comment by long2ice** [comment]
这里是有些问题，因为项目早期的代码是来自于另一个项目，突然想到跳过delete,update这些应该在producer在做而不是在consumer

**Comment by lenovore** [comment]
好的
