### ISSUE TITLE
consumer.py中is_insert的判断问题

### ISSUE THREAD

**Issue by lenovore** [long2ice/mysql2ch#3]
如果consumer出问题暂停了，producer正常，这样就会积压很多events。
当consumer恢复正常后，因为时间的问题，会导致event一条一条的执行。
![image](https://user-images.githubusercontent.com/29646774/79332208-fbfc1600-7f4e-11ea-9770-76eaf9f89e25.png)

正常情况下应该是下面这种
![image](https://user-images.githubusercontent.com/29646774/79332233-0c13f580-7f4f-11ea-9ced-a11bd144dfe9.png)

.env配置
INSERT_NUMS=20000
INSERT_INTERVAL=60

**Comment by long2ice** [comment]
确实有这个问题，已修复。
