### ISSUE TITLE
kafka的问题

### ISSUE THREAD

**Issue by lenovore** [long2ice/mysql2ch#4]
请教一下，目前遇到了这么一种情况：
kafka出错导致索引文件和日志文件时间戳不一致（可能是重启或zookeeper出问题或内存不足等原因）
producer.send正常发送，但是消费者无法消费。

网上搜索，大都是说删除索引文件，重启kafka。按照这种方式做了以后会导致消息（mysql数据）丢失，因为代码中producer.send正常（错误好像不影响send，暂未复现该情况），redis中的binlog位置会更新。

怎么才能让producer感知到kafka（容器单机部署非集群）出问题了，使其发送消息失败且不更新redis中的binlog的位置。
我试着将producer改成同步，但是感觉好像没关系。

报错信息
`ARN [Log partition=mysql2ch-4, dir=/var/lib/kafka/data] Found a corrupted index file corresponding to log file /var/lib/kafka/data/mysql2ch-4/00000000000000000000.log 
due to Corrupt time index found, time index file (/var/lib/kafka/data/mysql2ch-4/00000000000000000000.timeindex) 
has non-zero size but the last timestamp is 0 which is less than the first timestamp 1587959542575}, 
recovering segment and rebuilding index files... (kafka.log.Log)`

![clipboard](https://user-images.githubusercontent.com/29646774/80439047-35ae2300-8938-11ea-8073-b734f902521a.png)
![clipboard1](https://user-images.githubusercontent.com/29646774/80439057-38107d00-8938-11ea-888a-7244b7cc1a03.png)

我处理的方式是 删除每个分区中的.timeindex和.index文件，重启kafka。
结果导致了数据丢失，因为redis更新了位置

**Comment by long2ice** [comment]
kafka其实我也不是特别熟，只是会用而已，你可以使用``mysql2ch etl --schema test --tables test --renew``重新全量导入，如果mysql和clickhouse在同一局域网还是很快的，把kafka原来的topic删了，然后从最新的binlog开始生产和消费。

**Comment by lenovore** [comment]
好的 多谢
