### ISSUE TITLE
mysql添加新列导致数据同步出错

### ISSUE THREAD

**Issue by lenovore** [long2ice/mysql2ch#5]
mysql添加新列并在clickhouse中也添加该列后，依然报错。

因为拼接的插入clickhouse的sql语句是不带列名的，而insert数据有部分没有新列，有部分有，比如insert into tb values(...),(...,‘新列’)

是不是可以考虑获取clickhouse列名来进行添加，或者有其他更好的办法吗

**Comment by long2ice** [comment]
目前没有考虑clickhouse同步MySQL表结构，因为涉及到DDL监听与默认值等问题，现在最好的办法还是renew。

**Comment by lenovore** [comment]
好的
